---
- name: Install Python related stuff
  hosts: localhost
  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
        
    - name: Install python and pip
      apt:
        pkg:
          - python3
          - python3-pip
          - python3-dev
          - virtualenv
    
    - name: Install pyenv dependencies
      apt:
        pkg:
          - git
          - make
          - build-essential
          - libssl-dev
          - zlib1g-dev
          - libreadline-dev
          - libsqlite3-dev
          - wget
          - curl
          - llvm
          - libncurses5-dev
          - libncursesw5-dev
          - xz-utils
          - tk-dev
          - libbz2-dev
          
    - name: Download file with check (sha256)
      get_url:
        url: https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer 
        dest: /tmp/pyenv-installer.sh
        mode: 0777
    
    - name: Install using pyenv-installer
      shell: /tmp/pyenv-installer.sh
      
    - name: Install virtualenvwrapper
      pip:
        name: virtualenvwrapper